// var ul = document.querySelector('ul');
 
// var button = document.querySelector('button');

// button.addEventListener('click',function(){
//     var li = document.createElement('li');
//     li.textContent = 'new todos';
//     ul.prepend(li);
// })



// ul.addEventListener('click',function(e){
//     if(e.target.nodeName =='LI'){
//         e.target.remove();
//     }
//     console.log(e.target)
// });



